CREATE TABLE IF NOT EXISTS `user` (
	id BIGINT PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(255) NOT NULL,
	surname VARCHAR(255) NOT NULL,
	email VARCHAR(255) NOT NULL UNIQUE,
	password VARCHAR(255) NOT NULL
);
CREATE TABLE IF NOT EXISTS movie (
	id INT PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(255) NOT NULL,
	poster VARCHAR(255),
	overview TEXT,
	duration INT NOT NULL,
	genre VARCHAR(100),
	release_date DATE,
	imdb_id VARCHAR(255),
	film_id VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS cinema_hall (
	id INT PRIMARY KEY AUTO_INCREMENT,
	movie_id INT NOT NULL,
	movie_session DATETIME NOT NULL,
	CONSTRAINT fk_hall_movie FOREIGN KEY (movie_id) REFERENCES movie(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS seat (
    id INT PRIMARY KEY AUTO_INCREMENT,
    cinema_hall_id INT NOT NULL,
    seat_number VARCHAR(20) NOT NULL,
    status ENUM('AVAILABLE', 'RESERVED', 'BOOKED') DEFAULT 'AVAILABLE',
    CONSTRAINT fk_seat_hall FOREIGN KEY (cinema_hall_id) REFERENCES cinema_hall(id) ON DELETE CASCADE,
    UNIQUE (cinema_hall_id, seat_number)
);

CREATE TABLE IF NOT EXISTS orders (
	id VARCHAR(50) PRIMARY KEY,
	user_id BIGINT NOT NULL,
	cinema_hall_id INT NOT NULL,
	status ENUM('CREATED','CONFIRMED','CANCELLED', 'EXPIRED') DEFAULT 'CREATED', 
	payment_method ENUM ('MOMO', 'VNPAY', 'ZALOPAY', 'CASH') DEFAULT 'CASH',
	payment_status ENUM('PENDING', 'PAID', 'CANCELLED') DEFAULT 'PENDING',
	total_amount DECIMAL(10, 2) NOT NULL DEFAULT 0.00,
	order_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	expired_at DATETIME,
	CONSTRAINT fk_order_user FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE,
	CONSTRAINT fk_order_hall FOREIGN KEY (cinema_hall_id) REFERENCES cinema_hall(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS order_seat(
	id INT PRIMARY KEY AUTO_INCREMENT,
	order_id VARCHAR(50) NOT NULL,
	seat_id INT NOT NULL,
	price DECIMAL (10, 2) NOT NULL DEFAULT 0.00,
	CONSTRAINT fk_order_seat_order FOREIGN KEY (order_id) REFERENCES orders(id) ON DELETE CASCADE,
	CONSTRAINT fk_order_seat FOREIGN KEY (seat_id) REFERENCES seat(id) ON DELETE CASCADE	
);
